### ISSUE TITLE
tv4.asyncLoad([JSV.schema], function() 

### ISSUE THREAD

**Issue by amitdesai03** [jlblcc/json-schema-viewer#5]
Hi Josh,

I am trying to use your library but getting error at line:
tv4.asyncLoad([JSV.schema], function() 

Its says taht asyncLoad is not a function.

EDIT: SEEMS LIKES ITS PRESENT IN MIN.JS BUT NOT IN MAIN ONE.

Thanks

**Comment by jlblcc** [comment]
Yeah, that file's included in the minified build, but if you're using the main file it'll need to be included separately. It's in the [/lib directory](https://github.com/jlblcc/json-schema-viewer/blob/master/lib/tv4.async-load-jquery.js). FYI, you can use ```grunt prod``` to build the minified version(look in the 'prod' directory).

My intention was to try to get this added to the main tv4 repo as a plugin.

**Comment by amitdesai03** [comment]
Thanks
