### ISSUE TITLE
Drag and drop schema fields

### ISSUE THREAD

**Issue by amitdesai03** [jlblcc/json-schema-viewer#7]
Hi Josh,

I am working on project which requires visualy picking up schema elements and dropping in some container.

Container will finally have the elements which will indicate what data to parse from JSON response and throw away rest of JSON.

Do you think with your library I can do something similar?
Any heads up on how to do it? can you help?

Thanks.

-Amit

**Comment by amitdesai03** [comment]
Never mind...i decided to have checkbox next to each schema field instead of drag and drop..

**Comment by jlblcc** [comment]
FYI, you can look at [this D3 example](http://bl.ocks.org/robschmuecker/7880033) for ideas on implementing drag and drop. I actually borrowed code for JSV from this example.
